#!/usr/bin/env python

import sys
from time import sleep

def main(input_file, output_file):
    with open(input_file, 'r') as f:
        data = [int(i) for i in f.readline().split()]
    
    data.append(data[-1] + 2)
    sleep(4)

    with open(output_file, 'w') as f:
        f.write(' '.join(map(str, data)))

if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise RuntimeError('Usage: {} input output'.format(sys.argv[0]))
    input_file, output_file = sys.argv[1], sys.argv[2]
    main(input_file, output_file)
